//----------------------------------------------------------------------------
// Copyright (c) 2004-2015 Synchrotron SOLEIL
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the GNU Lesser Public License v3
// which accompanies this distribution, and is available at
// http://www.gnu.org/licenses/lgpl.html
//----------------------------------------------------------------------------
/*----- PROTECTED REGION ID(DynamicInterface.h) ENABLED START -----*/
//=============================================================================
//
// file :        DynamicInterface.h
//
// description : Include for the DynamicInterface class.
//
// project :     DynamicInterface.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DynamicInterface_H
#define DynamicInterface_H


#include <tango.h>
#include <yat4tango/DynamicInterfaceManager.h>

/*----- PROTECTED REGION END -----*/

/**
 *	DynamicInterface class Description:
 *	Forwards the attributes specified by the ForwardedAttributes property.
 *	Each forwarded attribute becomes a local dynamic attribute of the DynamicInterface device.
 *	ForwardedAttributes property is an array of strings (one entry per attribute to forward).
 *	Each entry should at least contains the fully qualified name of the attribute to be forwarded.
 *	An optional 'local attribute name' can also be specified in case you need/want to change the name under which the attribute is forwarded.
 *	Each ForwardedAttributes entry must have the following syntax: [tdb-host:tdb-port/]the/dev/name/attr-name[::attr-local-name].
 *	
 */

namespace DynamicInterface_ns
{
	/*----- PROTECTED REGION ID(DynamicInterface::Additional Class Declarations) ENABLED START -----*/

		//		Additional Class Declarations

	/*----- PROTECTED REGION END -----*/	//	DynamicInterface::Additional Class Declarations


class DynamicInterface : public Tango::Device_4Impl
{
	/*----- PROTECTED REGION ID(DynamicInterface::Data Members) ENABLED START -----*/

	//		Add your own data members

	/*----- PROTECTED REGION END -----*/	//	DynamicInterface::Data Members

//	Device property data members
public:
  Tango::DevShort attr1_val;
  Tango::DevShort attr2_val;
  Tango::DevShort attr3_val;

//	Attribute data members
public:



//	Constructors and destructors
public:
	/**
	 * Constructs a newly allocated Command object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DynamicInterface(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly allocated Command object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DynamicInterface(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly allocated Command object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	DynamicInterface(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The object destructor.
	 */	
	~DynamicInterface() {delete_device();};



//	Miscellaneous methods
public:
	/**
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/**
	 *	Initialize the device
	 */
	virtual void init_device();
	/**
	 *	Read the device properties from database
	 */
	 void get_device_property();
	/**
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


	/**
	 *	Method      : DynamicInterface::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */ 
	void add_dynamic_attributes();

//	Command related methods
public: 

	/*----- PROTECTED REGION ID(DynamicInterface::Additional Method prototypes) ENABLED START -----*/

	//	Additional Method prototypes

private:
  //- the dyn. cmds. execute callback
  void execute_callback (yat4tango::DynamicCommandExecuteCallbackData& cbd);
  
  //- the dyn. attrs. read callback
  void read_callback (yat4tango::DynamicAttributeReadCallbackData& cbd);

  //- the dyn. attrs. write callback
  void write_callback (yat4tango::DynamicAttributeWriteCallbackData& cbd);

  //- the dynamic attribute manager
  yat4tango::DynamicInterfaceManager m_dim;
  
	/*----- PROTECTED REGION END -----*/	//	DynamicInterface::Additional Method prototypes
};

	/*----- PROTECTED REGION ID(DynamicInterface::Additional Classes Definitions) ENABLED START -----*/

	//	Additional Classes definitions

	/*----- PROTECTED REGION END -----*/	//	DynamicInterface::Additional Classes Definitions

} //	namespace

#endif	//	DynamicInterface_H
