//----------------------------------------------------------------------------
// Copyright (c) 2004-2015 Synchrotron SOLEIL
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the GNU Lesser Public License v3
// which accompanies this distribution, and is available at
// http://www.gnu.org/licenses/lgpl.html
//----------------------------------------------------------------------------
/*----- PROTECTED REGION ID(AttributesForwarderStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        AttributesForwarderStateMachine.cpp
//
// description : C++ source for the �name� and its alowed
//               methods for commands and attributes
//
// project :     AttributesForwarder.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <AttributesForwarder.h>
#include <AttributesForwarderClass.h>

/*----- PROTECTED REGION END -----*/


/*
 * AttributesForwarder states description:
 *
 */

namespace AttributesForwarder_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================


	/*----- PROTECTED REGION ID(AttributesForwarder::are_dynamic_attributes_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic attributes are alowed

	/*----- PROTECTED REGION END -----*/	//	AttributesForwarder::are_dynamic_attributes_allowed


//=================================================
//		Commands Allowed Methods
//=================================================



	/*----- PROTECTED REGION ID(AttributesForwarder::are_dynamic_commands_allowed) ENABLED START -----*/

	//	Add your code to check if dynamic commands are alowed

	/*----- PROTECTED REGION END -----*/	//	AttributesForwarder::are_dynamic_commands_allowed

}	// namespace AttributesForwarder_ns
